### ISSUE TITLE
Link to demo doesn't load

### ISSUE THREAD

**Issue by photonstorm** [ad4game/phaser-a4g#2]
Hiya,

Great looking plugin! Sadly the link to your demo: http://xmmorpg.com/phaser-a4g/ returns a 'Forbidden' error and won't load. Doesn't matter too much, but as it's the first link in your README I guess a lot of people will try clicking it.

**Comment by kononenko-a-m** [comment]
Hi @photonstorm thanks for highlighting the issue! Our demo has been moved to http://xmmorpg.com/phaser-a4g/example

Also link in README has been fixed
